# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'travelPlanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for travelPlanner
pod 'Floaty', '~> 4.1.0'
  target 'travelPlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'travelPlannerUITests' do
    # Pods for testing
  end

end
